### ISSUE TITLE
Phase 0 Report

### ISSUE THREAD

**Issue by amirMahfoozi** [advanced-programming-sut-2023/project-group-28#1]
<div dir="rtl" align='right'>

# فاز 0

## کارهایی که باید در فاز 0 انجام دهید

<details>
  <summary>راه‌اندازی مخزن GItHub</summary>

  <div dir="ltr" align='right'>

  1. [x] شروع نشده
  2. [x] در حال انجام
  3. [x] تمام شده
  </div>
</details>

<details>
  <summary>راه‌اندازی GitHub Issue</summary>
  
  <div  dir="ltr" align='right'>
  
  1. [x] شروع نشده
  2. [x] در حال انجام
  3. [x] تمام شده
     </div>
</details>

<details>
  <summary>طراحی UML برای منطق پروژه</summary>
  
  <div  dir="ltr" align='right'>
  
  1. [x] شروع نشده
  2. [x] در حال انجام
  3. [x] تمام شده
     </div>
</details>

## تسک‌های نفر اول
  **نام و نام خانوادگی:سپهر ذوالفقاری** 
<details>
  <summary>کامیت نام و شماره دانشجویی در README</summary>

  <div dir="ltr" align='right'>

  1. [x] شروع نشده
  2. [x] در حال انجام
  3. [x] تمام شده
  </div>
</details>
<details>
  <summary>طراحی UML برای منطق پروژه</summary>

  <div dir="ltr" align='right'>

  1. [x] شروع نشده
  2. [x] در حال انجام
  3. [x] تمام شده
  </div>
</details>
## تسک‌های نفر دوم

  **نام و نام خانوادگی:امیر محمد محفوظی**
<details>
  <summary>کامیت نام و شماره دانشجویی در README</summary>

  <div dir="ltr" align='right'>

  1. [x] شروع نشده
  2. [x] در حال انجام
  3. [x] تمام شده
  </div>
</details>
<details>
  <summary>طراحی UML برای منطق پروژه</summary>

  <div dir="ltr" align='right'>

  1. [x] شروع نشده
  2. [x] در حال انجام
  3. [x] تمام شده
  </div>
</details>
## تسک‌های نفر سوم

  **نام و نام خانوادگی:رادین چراغی**
<details>
  <summary>کامیت نام و شماره دانشجویی در README</summary>

  <div dir="ltr" align='right'>

  1. [x] شروع نشده
  2. [x] در حال انجام
  3. [x] تمام شده
  </div>
</details>
<details>
  <summary>طراحی UML برای منطق پروژه</summary>

  <div dir="ltr" align='right'>

  1. [x] شروع نشده
  2. [x] در حال انجام
  3. [x] تمام شده
  </div>
</details>
</div>

**Comment by sepehrzoli** [comment]
salam

**Comment by amirMahfoozi** [comment]
Phase 0 completed !
